import {
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Circle,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Music,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  PlugZap,
  PlusCircle,
  Repeat,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TreePalm,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

/** Curated icon set for categories/accounts/goals — keys are stored in the DB. */
export const FINANCE_ICONS: Record<string, LucideIcon> = {
  'banknote': Banknote,
  'bike': Bike,
  'book-open': BookOpen,
  'briefcase': Briefcase,
  'bus': Bus,
  'car': Car,
  'circle': Circle,
  'circle-ellipsis': CircleEllipsis,
  'clapperboard': Clapperboard,
  'coffee': Coffee,
  'credit-card': CreditCard,
  'dumbbell': Dumbbell,
  'flame': Flame,
  'fuel': Fuel,
  'gamepad-2': Gamepad2,
  'gift': Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'heart': Heart,
  'heart-pulse': HeartPulse,
  'home': Home,
  'landmark': Landmark,
  'laptop': Laptop,
  'music': Music,
  'paw-print': PawPrint,
  'phone': Phone,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'plane': Plane,
  'plug-zap': PlugZap,
  'plus-circle': PlusCircle,
  'repeat': Repeat,
  'shield': Shield,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'store': Store,
  'target': Target,
  'tree-palm': TreePalm,
  'trending-up': TrendingUp,
  'users': Users,
  'utensils': Utensils,
  'wallet': Wallet,
  'wifi': Wifi,
  'wrench': Wrench,
};

export function financeIcon(name?: string | null): LucideIcon {
  return (name && FINANCE_ICONS[name]) || Circle;
}

export const ICON_NAMES = Object.keys(FINANCE_ICONS);

/** Swatches offered by the color picker. */
export const FINANCE_COLORS = [
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#84cc16',
  '#22c55e',
  '#10b981',
  '#14b8a6',
  '#06b6d4',
  '#3b82f6',
  '#6366f1',
  '#8b5cf6',
  '#d946ef',
  '#ec4899',
  '#64748b',
];
