import { Router } from 'express';
import { authRouter } from './modules/auth/auth.router.js';
import { usersRouter } from './modules/users/users.router.js';
import { accountsRouter } from './modules/accounts/accounts.router.js';
import { categoriesRouter } from './modules/categories/categories.router.js';
import { transactionsRouter } from './modules/transactions/transactions.router.js';
import { recurringRouter } from './modules/recurring/recurring.router.js';
import { budgetsRouter } from './modules/budgets/budgets.router.js';
import { analyticsRouter } from './modules/analytics/analytics.router.js';
import { dashboardRouter } from './modules/dashboard/dashboard.router.js';
import { aiRouter } from './modules/ai/ai.router.js';
import { notificationsRouter } from './modules/notifications/notifications.router.js';
import { householdRouter } from './modules/household/household.router.js';
import { ledgerRouter } from './modules/ledger/ledger.router.js';
import { exchangeRatesRouter } from './modules/exchange-rates/exchange-rates.router.js';
import { wishlistRouter } from './modules/wishlist/wishlist.router.js';
import { guidesRouter } from './modules/guides/guides.router.js';
import { devicesRouter } from './modules/devices/devices.router.js';
import { ingestRouter } from './modules/ingest/ingest.router.js';
import { appRouter } from './modules/app/app.router.js';
import { moneyRouter } from './modules/money/money.router.js';
import { fundingRouter } from './modules/funding/funding.router.js';
import { searchRouter } from './modules/search/search.router.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/accounts', accountsRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/transactions', transactionsRouter);
apiRouter.use('/recurring', recurringRouter);
apiRouter.use('/budgets', budgetsRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/household', householdRouter);
apiRouter.use('/ledger', ledgerRouter);
apiRouter.use('/exchange-rates', exchangeRatesRouter);
apiRouter.use('/wishlist', wishlistRouter);
apiRouter.use('/guides', guidesRouter);
apiRouter.use('/devices', devicesRouter);
apiRouter.use('/ingest', ingestRouter);
apiRouter.use('/app', appRouter);
// Recent movements, undo, and the Money Doctor.
apiRouter.use('/money', moneyRouter);
// Payday rules: "when my salary lands, fill these plans, in this order".
apiRouter.use('/funding', fundingRouter);
