import { Router } from 'express';
import { authRouter } from './modules/auth/auth.router.js';
import { usersRouter } from './modules/users/users.router.js';
import { accountsRouter } from './modules/accounts/accounts.router.js';
import { categoriesRouter } from './modules/categories/categories.router.js';
import { transactionsRouter } from './modules/transactions/transactions.router.js';
import { recurringRouter } from './modules/recurring/recurring.router.js';
import { budgetsRouter } from './modules/budgets/budgets.router.js';
import { goalsRouter } from './modules/goals/goals.router.js';
import { analyticsRouter } from './modules/analytics/analytics.router.js';
import { dashboardRouter } from './modules/dashboard/dashboard.router.js';
import { aiRouter } from './modules/ai/ai.router.js';
import { notificationsRouter } from './modules/notifications/notifications.router.js';
import { householdRouter } from './modules/household/household.router.js';
import { ledgerRouter } from './modules/ledger/ledger.router.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/accounts', accountsRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/transactions', transactionsRouter);
apiRouter.use('/recurring', recurringRouter);
apiRouter.use('/budgets', budgetsRouter);
apiRouter.use('/goals', goalsRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/household', householdRouter);
apiRouter.use('/ledger', ledgerRouter);
